symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    # https://github.com/SymfonyCasts/reset-password-bundle
    lifetime: 1800
    throttle_limit: 10
